### ISSUE TITLE
Scrolling feels delayed/laggy

### ISSUE THREAD

**Issue by Tech-Tac** [dridino/smooth_list_view#5] opened 2024-12-22 15:26 UTC
Just compare smoothScroll: true and smoothScroll: false, or alternatively set duration to 1 millisecond with smoothScroll: true, on Windows with a populated list of real data, around 400 items, complex builders.

**Comment by dridino** [comment] 2024-12-22 19:43
I tested it with a list of 400 items by toggling `smoothScroll` on and off and it worked fine. Please note that setting `smoothScroll` to `false` and setting the duration of the animation to 1ms is actually very different. In the first case you ask it to skip the animation while in the second you ask it to perform the animation in only 1ms.
If your display has a 60Hz refresh rate, it draws a new image every 16.66 ms, so you wouldn't be able to see a 1ms animation, that's why it looks like the `SmoothListView` is jumping between positions. Moreover, by setting the duration to only 1ms, you're demanding a lot of calculation in a very short period of time, which causes it to be laggy.
If you still find the scroll laggy when setting the duration to an acceptable value (like 250ms as shown in the example code of one of the other issues you opened) then please provide an example so I can reproduce it, otherwise if it's not related to the package itself, I'll have to close the issue.

**Comment by Tech-Tac** [comment] 2024-12-22 19:49
I think that was just an issue on my (low) end, but this doesn't stop it from feeling kinda weird compared to other smooth scrolling apps, like Chrome for example, but I can't put my finger on what exactly is wrong

**Comment by dridino** [comment] 2024-12-22 21:55
I'm glad your problem is solved.
I think experimenting with different curves and duration to match Chrome's feeling is the only solution here
Is this okay if i close this issue then ?

**Comment by Tech-Tac** [comment] 2024-12-22 22:05
Feel free to do so, I think this is just intended behavior but it unfortunately doesn't fit my use case apparently.

I ended up using a modified version of the modified version of the code provided in this comment in a Flutter issue: https://github.com/flutter/flutter/issues/32120#issuecomment-1937407520

It seems to work fine, combined with SuperListView.

**Comment by dridino** [comment] 2024-12-22 22:15
Okay, I'm happy you found something matching your needs :)

**Closed as completed by dridino** 2024-12-22 22:15 UTC
